services:
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/.chroma
    restart: always

volumes:
  chroma_data:
